import udftools-1.0.0b2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1374,7 +1374,7 @@ fi
 
 # Define the identity of the package.
 PACKAGE=udftools
-VERSION=2.0
+VERSION=1.0.0b2
 
 cat >>confdefs.h <<EOF
 #define PACKAGE "$PACKAGE"
@@ -7066,11 +7066,11 @@ if test `eval echo '${'$as_ac_var'}'` = yes; then
 EOF
 
 else
-  LIBOBJS="$LIBOBJS getopt.o"
+  LIBOBJS="$LIBOBJS getopt.lo"
 fi
 done
 
-ac_config_files="$ac_config_files Makefile libudffs/Makefile mkudffs/Makefile cdrwtool/Makefile pktsetup/Makefile"
+ac_config_files="$ac_config_files Makefile libudffs/Makefile mkudffs/Makefile cdrwtool/Makefile pktsetup/Makefile doc/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -7395,9 +7395,10 @@ do
   "mkudffs/Makefile" ) CONFIG_FILES="$CONFIG_FILES mkudffs/Makefile" ;;
   "cdrwtool/Makefile" ) CONFIG_FILES="$CONFIG_FILES cdrwtool/Makefile" ;;
   "pktsetup/Makefile" ) CONFIG_FILES="$CONFIG_FILES pktsetup/Makefile" ;;
+  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h:include/config.in" ;;
-  *) { { echo "$as_me:7400: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:7401: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7639,7 +7640,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7642: creating $ac_file" >&5
+    { echo "$as_me:7643: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7657,7 +7658,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7660: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7661: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7670,7 +7671,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7673: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7674: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7731,7 +7732,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:7734: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:7735: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -7742,7 +7743,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7745: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7746: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7755,7 +7756,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7758: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7759: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7872,7 +7873,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:7875: $ac_file is unchanged" >&5
+      { echo "$as_me:7876: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
